version: '3.8'
name: 'local'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
    env_file:
      - ./env/.mongo.env
